function p = a_cpath(p)

input = {'/data_wks16/tetdata/klusters/dino4Osc', ...
         '/data_wks16/tetdata/klusters', ...
         '/data_wks16/tetdata', ...
         '/data/tetdata/matlab', ...
         '/data/tetdata', ...
         '/data/a/experiments', ...
         '/data_san2/tetdata', ...
         '/data_san2/klusters', ...
         '/g', ...
         '/h', ...
         '/usr/lab/projects/andreas/tet/data', ...
         };

% local aliases
base = getLocalPath('/stor01/mpi/');
local = {[base 'klusters/dino4'], ...
         [base 'klusters'], ...
         [base 'tetdata'], ...
         [base 'matlab'], ...
         [base 'tetdata'], ...
         [base 'experiments'], ...
         [base 'tetdata'], ...
         [base 'klusters'], ...
         [base 'tetdata'], ...
         [base 'tetdata'], ...
         [base 'qnx'], ...
         };

% convert path
for i = 1:length(input)
    n = length(input{i});
    if strncmp(p,input{i},n)
        p = [local{i}, p(n+1:end)];
        break;
    end
end
